export const countries = [
    { code: 'US', name: 'United States', dialCode: '+1' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44' },
    { code: 'IN', name: 'India', dialCode: '+91' },
    { code: 'AU', name: 'Australia', dialCode: '+61' },
    { code: 'CA', name: 'Canada', dialCode: '+1' },
    { code: 'NP', name: 'Nepal', dialCode: '+977' },
    { code: 'CN', name: 'China', dialCode: '+86' },
    { code: 'JP', name: 'Japan', dialCode: '+81' },
    { code: 'KR', name: 'South Korea', dialCode: '+82' },
    { code: 'FR', name: 'France', dialCode: '+33' },
    { code: 'DE', name: 'Germany', dialCode: '+49' },
    { code: 'IT', name: 'Italy', dialCode: '+39' },
    { code: 'ES', name: 'Spain', dialCode: '+34' },
    { code: 'NL', name: 'Netherlands', dialCode: '+31' },
    { code: 'CH', name: 'Switzerland', dialCode: '+41' },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64' },
    { code: 'SG', name: 'Singapore', dialCode: '+65' },
    { code: 'MY', name: 'Malaysia', dialCode: '+60' },
    { code: 'TH', name: 'Thailand', dialCode: '+66' },
    { code: 'PH', name: 'Philippines', dialCode: '+63' },
]
